language: php

php:
  - 8.0
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin:$HOME/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
  - composer global require drupal/coder
  - composer global require mglaman/phpstan-drupal

script:
  - find . -name \*.php -exec php -l {} \;
  - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,info --ignore=node_modules,bower_components,vendor .
  - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info --ignore=node_modules,bower_components,vendor .
  - phpstan
